### ISSUE TITLE
Página de contribuidores

### ISSUE THREAD

**Issue by ruanltbg** [jquery-br/jQuery-Brasil#11]
É uma página nova, com a listagem de todos os contribuidores do site (seja via post ou code)

Um exemplo legal: http://events.jquery.org/2011/boston/speakers/

**Comment by felquis** [comment]
Top! Quem seria os contribuidores? O pessoal que contribui com posts ou
quem contribui no github também?

2013/1/28 Ruan Carlos notifications@github.com

> É uma página nova, com a listagem de todos os contribuidores do site (seja
> via post ou code)
> 
> Um exemplo legal: http://events.jquery.org/2011/boston/speakers/
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jquery-br/jQuery-Brasil/issues/11.

## 

Ofelquis Gimenes
Desenvolvedor Front-End
http://tutsmais.com.br/ http://tutsmais.com.br/blog/
http://devcastbrasil.com/ http://www.devcastbrasil.com/

**Comment by ruanltbg** [comment]
Como diz no texto: É uma página nova, com a listagem de todos os contribuidores do site (seja via **post** ou **code**)
