### ISSUE TITLE
Comentários via DISQUS

### ISSUE THREAD

**Issue by ruanltbg** [jquery-br/jQuery-Brasil#12]
Alterar comentários para ser via DISQUS.

Precisamos ver se mantemos os comentários antigos ou não.

**Comment by DiegoLopesLima** [comment]
O DISQUS tem suporte a bbcode?
É que um dos problemas que observei foi que algumas pessoas colam partes de código nos comentários, e acaba saindo errado muitas vezes...
O sistema está interpretando os comentários como código, então se alguém posta por exemplo:

``` javascript
$('<div>', {id:'jQuery'});
```

Ele acaba interpretando `<div>` como uma tag e quebra o código...
É possível observar isso nos comentários deste post por exemplo : [Criando elementos com jQuery](http://jquerybrasil.org/criando-elementos-com-jquery/#comment-12425).

**Comment by ruanltbg** [comment]
Mesmo que tenha suporte, não é para ser usado, discussões sobre código devem ser mantidas no grupo e não no site. O grupo foi criado justamente para isso. Devemos criar um padrão: Para cada post deve ser criado um tópico no grupo, onde o post deve ter um link para lá. Nenhum comentário com código deve ser aceito.

**Comment by felquis** [comment]
Diego, este artigo pode te ajudar
http://help.disqus.com/customer/portal/articles/665057 testei mas não deu
certo.

Em 29 de janeiro de 2013 12:27, Ruan Carlos notifications@github.comescreveu:

> Mesmo que tenha suporte, não é para ser usado, discussões sobre código
> devem ser mantidas no grupo e não no site. O grupo foi criado justamente
> para isso. Devemos criar um padrão: Para cada post deve ser criado um
> tópico no grupo, onde o post deve ter um link para lá. Nenhum comentário
> com código deve ser aceito.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jquery-br/jQuery-Brasil/issues/12#issuecomment-12836703.

## 

Ofelquis Gimenes
Desenvolvedor Front-End
http://tutsmais.com.br/ http://tutsmais.com.br/blog/
http://devcastbrasil.com/ http://www.devcastbrasil.com/

**Comment by ruanltbg** [comment]
Vale lembrar que o sistema atual tbm tem isso, se vc colocar [js] texte [/js] ele já interpreta direito.

**Comment by DiegoLopesLima** [comment]
Sim, só não encontrei nada informando para os usuários. Então eles continuam comentando e colando códigos de forma errada.
