### ISSUE TITLE
Usar o DISQUS para comentários

### ISSUE THREAD

**Issue by felquis** [jquery-br/jQuery-Brasil#3]
Digamos que, essa plataforma de comentários, é a melhor coisa que existe, o que acham de usa-la? [Aqui](http://loopinfinito.com.br/2013/01/09/a-historia-do-user-agent-string/) tem um exemplo dela funcionando, e [aqui](http://disqus.com/) o site dela.
![vomitando-arco-iris-gif](https://f.cloud.github.com/assets/736728/80167/0f3e6ef4-6227-11e2-8925-bf1ae4869986.gif)

**Comment by ruanltbg** [comment]
Adicionado na issue #6 @felquis
