### ISSUE TITLE
Adicionar link para download do jQuery

### ISSUE THREAD

**Issue by felquis** [jquery-br/jQuery-Brasil#4]
Não estou conseguindo acessar o site do jquerybrasil.org agora pra saber se existe essa feature.

Sempre que eu digito jQuery no Chrome, ele completa para jquerybrasil.org, e sempre que eu digito jquery é por que eu estou afim de baixar a ultima versão do jQuery. Então proponho que se tiver o link para download do jquery, igual no site do jQuery tem, seria fantástico.

![tumblr_m251dewND91r0n36o](https://f.cloud.github.com/assets/736728/80170/f1b6e2a2-6227-11e2-976a-4f01f80dbaf0.png)

**Comment by ruanltbg** [comment]
@felquis já existe sim (vou atualizar agora hehe) http://jquerybrasil.org/download/

**Comment by felquis** [comment]
Eu estou falando de alguma coisa como na imagem, clicou baixou. Não um tutorial de como baixar o jQuery.
![Captura de tela de 2013-01-19 15:12:12](https://f.cloud.github.com/assets/736728/80446/63ee7b54-625b-11e2-88dc-8fea3e91306b.png)

**Comment by ruanltbg** [comment]
Entendo e concordo. Adicionado na #6
