### ISSUE TITLE
Novo layout

### ISSUE THREAD

**Issue by DiegoLopesLima** [jquery-br/jQuery-Brasil#5]
- [ ] Usar estilo baseado no tema do <a href="https://github.com/jquery/jquery-wp-content/blob/master/themes/plugins.jquery.com/style.css" target="_blank">jQuery Plugins Site</a>.
- [ ] Exibir apenas uma breve descrição acompanhada de uma miniatura na listagem das postagens.
- [ ] Exibir as postagens em placas assim como no <a href="http://www.frontendbrasil.com.br/" target="_blank">www.frontendbrasil.com.br</a>.
- [ ] Escolher e aplicar uma cor diferente para o tema.
- [ ] Implementar botão <a href="https://github.com/jquery-br/jQuery-Brasil" target="_blank">Fork on Github</a>.

**Comment by ruanltbg** [comment]
@DiegoLopesLima não acho que seja necessário ter uma área de eventos já que o http://braziljs.org/eventos/ já mantem uma lista atualizado, não tem o porque duplicarmos conteúdo.

O botão do github é uma boa vou add ele na #6

**Comment by felquis** [comment]
Issues repetidas 
![some_of_the_best_gifs_of_2012_191](https://f.cloud.github.com/assets/736728/80509/3e0d19c2-6265-11e2-82c2-509c1104d1f5.gif)

**Comment by DiegoLopesLima** [comment]
Verdade, realmente não há fundamento em uma área de eventos. Retirei da lista.

**Comment by felquis** [comment]
Não é melhor deixar o conteúdo todo na issue #6 ? Tem duas issues pra mesma coisa.

![some_of_the_best_gifs_of_2012_25](https://f.cloud.github.com/assets/736728/80516/9819b528-6266-11e2-9fa7-70eb6d776a01.gif)

**Comment by DiegoLopesLima** [comment]
Sim, o @ruanltbg já está fazendo isso. Fechando...
