### ISSUE TITLE
Novo layout

### ISSUE THREAD

**Issue by ruanltbg** [jquery-br/jQuery-Brasil#6]
O novo layout deverá ser baseado no novo layout dos sites do jQuery.
### Header
- Link para download do jquery (assim como tem na home do jquery).
- Botão do fork on github
#### Home:

Posts delimitados nesse estilo:
http://buildinternet.com/category/tutorials/
#### Post/Páginas:

O padrão da página de plugins do site do jquery é muito bom, poderiamos nos basear nela.
http://plugins.jquery.com/validate/
#### Autores:

Poderá seguir o mesmo padrão das outras páginas com a descrição e alguns links na parte superior
#### Contribuidores

A página de contribuidores poderia ser nesse estilo
http://events.jquery.org/2011/boston/speakers/
#### Comentários:

Usar o DISQUS.
#### Licença:

Adicionar a licença: http://creativecommons.org/choose/

**Comment by felquis** [comment]
@ruanltbg Cria um Milestone com nome "Novo tema" para centralizar nele todas as issues referentes ao novo layout.

Assim, quando for criar a issue, indique que a issue faz parte do Milestone "Novo tema", ai vai ficar lindo.

**Comment by felquis** [comment]
@ruanltbg outra coisa, o que tu acha de criar um tag do tema atual? Outra coisa, tu vai criar um branch tipo "novoTema"?

![vomitando-arco-iris-gif](https://f.cloud.github.com/assets/736728/80524/8623da68-6268-11e2-9c9a-cc2a41006156.gif)

**Comment by ruanltbg** [comment]
@felquis sim estou preparando tudo agora.

**Comment by DiegoLopesLima** [comment]
Estou de acordo com todas essas sugestões...
Tenho certeza que vão melhorar muito o site.

**Comment by yuricamara** [comment]
Tb curti!

**Comment by DiegoLopesLima** [comment]
Implementar botões para compartilhamento das postagens.
- Google +
- Twitter
- Facebook

**Comment by felquis** [comment]
Sei que irão querer me matar, mas

### Vamos criar o novo site com [Jekyll](https://github.com/mojombo/jekyll)? :+1:

![cachorro](https://f.cloud.github.com/assets/736728/83851/37032d0c-63f4-11e2-839a-47b1d1c54cc8.gif)

**Comment by ruanltbg** [comment]
@felquis o que precisa ser mudado é o layout não a plataforma.

**Comment by DiegoLopesLima** [comment]
Sim... Acho que não há necessidade de mudar a plataforma...
Até por que se fossemos fazer isso, alguém teria que migrar todos as postagens, e ainda teria que entrar direto no banco de dados para empurrar os comentários...
Nem compensa...

**Comment by felquis** [comment]
<img src="https://f.cloud.github.com/assets/736728/83882/65e35e2a-63f5-11e2-88f4-b8112394c787.gif" width="200" />

**Comment by djalmaaraujo** [comment]
Vocês sabem conversar sem meme? ;)

**Comment by felquis** [comment]
<img src="https://f.cloud.github.com/assets/736728/83894/e03f98e6-63f5-11e2-81ed-0e3e53ffeb70.JPG" width="250" />

**Comment by felquis** [comment]
okay, parei.

**Comment by luiztiago** [comment]
lol

**Comment by DiegoLopesLima** [comment]
Bom...
A ideia é utilizar o mesmo tema do atual site de plugins do jQuery...
Este tema também foi usado para outros serviços do jQuery sempre alterando a cor... Então temos que escolher uma cor para a versão que vamos usar... Ex: O jQuery UI está com `#B24926` e o jQuery Plugins está com `#0769AD`.
O que acham de `#0A0`?
Caso queiram efetuar o teste, o seletor referente a mudança da cor é o `.jquery-ui #container`.

**Comment by felquis** [comment]
Acho que vale a pena, esperar sair o novo layout do jquery.com, visto que o jqueryui e jquery mobile já foram atualizados com o novo layout, só falta o jquery.com ai usamos o mesmo tema =D

**Comment by DiegoLopesLima** [comment]
Eu não concordo...
A ideia de usar o mesmo tema é bacana, mas a mesma cor não é legal...
Podemos ver outras cores... Esse é o verde da bandeira brasileira ^^: `#00A859`.

**Comment by felquis** [comment]
Não disse a mesma cor, e sim o mesmo layout.. estrutura do novo design que o jquery esta adotando.

**Comment by DiegoLopesLima** [comment]
É a mesma do jQuery Plugins e do jQuery UI...
Já estão adotando para todos os projetos... Está no repositório...
Eles só mudam as cores conforme o projeto...
